### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Zumbalamambo** [woodfrog/ActionRecognition#2]
can you please share the pretrained model for testing?

**Comment by woodfrog** [comment]
Hi, I'm sorry the pre-trained weights have been deleted when cleaning up the disk. But why don't you train it by yourself since the fine-tuning is actually quite simple and it won't take lots of time.

Or if you have to get some pre-trained model for action recognition, maybe [C3D](https://arxiv.org/pdf/1412.0767.pdf) is also a good fit for you. And there are quite a few repos providing pre-trained C3D model(e.g. https://github.com/hx173149/C3D-tensorflow).
